@extends('front.master')

@section('content')

	<!-- Start main-content -->
	<section class="page-title" style="background-image: url({{asset('images/slide-bg.jpg')}});">
		<div class="auto-container">
			<div class="title-outer text-center">
				<h1 class="title">Terms And Conditions</h1>
				<ul class="page-breadcrumb">
					<li><a href="{{route('front_page')}}">Home</a></li>
					<li>Terms And Conditions</li>
				</ul>
			</div>
		</div>
	</section>
	<!-- end main-content -->
    <style>
        .terms * {
            font-size: 14pt !important;
        }
    </style>

    <section class="mt-2 terms">
        <div class="container">
            <p><span style="font-size:11pt;font-family:Calibri,sans-serif;">INSTATOW LLC</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">OUR ADDRESS</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Shipping agent: (HANDELING EMPLOYEE)</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Phone: (HANDELING EMPLOYEE)</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Email: (HANDELING EMPLOYEE)</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">1.Shipper Information</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">.first name</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">.last name:&nbsp;</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">.phone1:</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">.phone2:</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">.cell:</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">.email:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">2. Pricing and Shipping</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">.order#</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">.calculated rate:</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">.1</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><sup><span style="font-size:0.6em;">st</span></sup></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">&nbsp;available date:</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">.hauler type: (open/enclosed)</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">.vehicle(s)runs:</span></p>
<p><u><span style="font-size:11pt;font-family:Calibri,sans-serif;">3. Transit Directives</span></u></p>
<p><u><span style="font-size:11pt;font-family:Calibri,sans-serif;">Origin</span></u></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Name:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Company:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Phone 1:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Phone 2:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Phone 3:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Address:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">City:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">State/Zip:</span></p>
<p><u><span style="font-size:11pt;font-family:Calibri,sans-serif;">Destination</span></u><u><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span></u><span style="font-size:11pt;font-family:Calibri,sans-serif;">Name:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Company:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Phone 1:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Phone 2:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Phone 3:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Address:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">City:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">State/Zip:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">4.Vehicle Information</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Year/Make/Model</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Type</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Color</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Lic. Plate</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">VIN</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Lot Num</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Tariff</span></p>
<p><br></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">5. Additional Information, Instructions, and/or Conditions</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">6. Agreed &amp; Accepted</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">By signing this document, I confirm that I&apos;ve fully read Terms &amp; Conditions, Cancellations and fees listed below. From this moment I don&rsquo;t have any questions to content and I&apos;m taking my obligations to honor this Contract and accepting Terms &amp; Conditions. I confirm that all information above was clearly disclosed to me.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Signature and Print Name:_________________________</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Date:_______1___________</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">7. Cancellations and Fees</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">1. If Client&apos;s vehicle is not picked up within 5 business days from the first available date Client can opt out of this agreement with no penalties.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">2. Failure to release vehicle(s) for any reason (including but not limited to: storage, auction, port, towing, mechanical, purchase fees, scheduling or personal issues, etc. ) after carrier assigned to the order may result in cancellation and/or a &apos;Dry Run&apos; fee additional to the deposit amount. The standard fee for &apos;Dry-Run&apos; is Two Hundred Dollars ($200.00).</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">3. After a specific carrier had been assigned to the client&apos;s order, the deposit amount is due and will be authorized (blocked) to the credit card provided, and charged after actual pick up. The balance should be paid via cash or any certified funds (money order, cashiers check) on delivery if other is not specified.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">4. After the carrier had been assigned deposit is due and becomes non-refundable, Refusal of Carrier or Cancellation might result Ina $150 rescheduling fee that will be charged in addition to the deposit, on the credit card provided. Refusal or Cancellation must be submitted by the client in writing to our email&nbsp;</span><span style="background-color:#ffff00;font-size:11pt;font-family:Calibri,sans-serif;">info@instatow.net</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">5. After the Contract has been signed all the preliminary agreements, discussions and correspondence between the Parties concerning this Contract are to be considered null and void, and shall be forfeited.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">6. Client&apos;s request for payment terms change after the carrier was assigned might result in additional bank surcharge of 4%.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">7. IMPORTANT! It is Clients obligation to request and fill out Bill of Lading/Condition report at the time of pick-up and delivery, to make sure all damages are marked properly and KEEP your copy until final delivery. It is a mandatory requirement and a proof to claim reimbursement from carriers insurance company. - This contract is a subject to all of the terms and conditions of Carrier&rsquo;s straight bill of lading and any liability exclusions therein. INSTATOW LLC has no responsibility or liability for any damage to a vehicle(s) and/or the contents of said vehicle(s) during transport or at any other time. The vehicle is insured by the Carrier&rsquo;sinsurance policy.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">8. PLEASE!!! IMPORTANT! You have to inform us of any modifications your vehicle has, that make the size or the weight of your vehicle different from stock parameters to avoid unexpected shipping charges.</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">9. If there are any changes to the original agreement, INSTATOW.NET has to inform the client prior to assigning a carrier, for final confirmation.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">10. INSTATOW.NET reserves the right of assigning a carrier to the client&apos;s order if all the original terms are met without additional client&rsquo;s confirmation.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">11. Calculated rate reflects the price that had been calculated based on the average accepted rate on this or similar routes. Calculated rate is a subject for driver&apos;s confirmation.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">12. INSTATOW LLC (INSTATOW.NET) reserves a right to opt out of the shipping contract in case of inability to assign a carrier for original price and conditions due to everyday changing carrier availability. In this case, INSTATOW LLC will try to offer alternative shipping option for client consideration. By signing the contract client agrees to current full terms and conditions list on our website.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">8. Terms &amp; Conditions</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">INSTATOW LLC is a fully licensed and bonded broker company registered with the USDOT4338302 with MC number 1694708. This agreement is solely between the customer and his/her or its duly authorized agents, (hereinafter referred to as &quot;Customer&rdquo; or &ldquo;Client&quot;), and INSTATOW LLC, DBA INSTATOW.NET.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Contract Terms and Liability Disclaimer</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">1. Client understands that by providing pickup and delivery addresses of vehicle(s) and/or credit card details is hiring the services of INSTATOW LLC, a federally licensed and bonded transportation brokerage (MC# 066459), to arrange the shipment of Client&rsquo;s vehicle(s) with a federally licensed and insured Contract Carrier (hereinafter referred to as &lsquo;Carrier&rsquo;). Furthermore, Client has thoroughly read and completely understands this agreement and will abide by these terms and conditions.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">2. The client must be a registered legal owner of the vehicle(s) and have the authority to enter into this Agreement or has been duly authorized by the legal owner of the vehicle(s) to enter into this Agreement.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">3. INSTATOW LLC agrees to provide a reliable and insured carrier to transport vehicle(s) as promptly as possible in conformance with Client&rsquo;s instructions but cannot guarantee pickup and/or delivery on a specific date or time. The client may request pick updates, but understands that while INSTATOW LLC will do all that can be done to meet Client&rsquo;s requests, due to the nature of the industry, such dates can only be requested and not guaranteed. Once a carrier is assigned to transport vehicle(s), Client will begiven the projected dates of pickup and delivery as well as the Carrier name and direct phone number. Any dates given by INSTATOW LLC are Carrier&rsquo;s computations only and are provided solely to assist the Client and Carrier in the arrangement of their schedules. Dates provided for pick up or delivery are never guaranteed, as certain conditions can alter a Carrier&rsquo;s schedule ( i.e. Weather and road conditions, scheduling or mechanical issues, a late customer, etc. ). As such, Client may never hold INSTATOW LLC liable for costs incurred as the result of any delays, including (but not limited to) any car rental fees or accommodation fees for Client. Also, Client understands and agrees to make themselves and/or Client&rsquo;s designated agent(s) (hereinafter referred to as &ldquo;Agent&rdquo;) available at all times necessary through phone, email or fax numbers provided to INSTATOW LLC for any transport related issues until delivery of the vehicle. INSTATOW LLC nor Carrier give no guarantees regarding pick up or delivery times and dates. INSTATOW LLC /Carrier shall not be held responsible for loss or damages occasioned by delays of any kind or for any reason. INSTATOW LLC/Carrier shall not be held liable for the failure of mechanical or operating parts of Customer&apos;s vehicle.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">4. The total price for the transportation is factored using numerous pieces of information including (but not limited to) the size and/or weight of the vehicle(s). Misrepresentation to INSTATOW LLC of the vehicle(s) size, weight and/or any modifications may result in additional fees and/or cancellation of the order. Modifications include (but are not limited to): extended cab, crew cab, long bed, diesel, 4&times;4, dually, side steps, flip top conversion vans, extended length cargo vans, oversized (non-stock) tires and/or rims, lift kits, roof /ladder racks, lowered, ground effects, spoilers, fog lights, tool boxes, etc. Deposits are never refunded in orders canceled due to misrepresentation of the vehicle(s). Any additional charges due to misrepresentation of weight, modifications or vehicle condition must be solved directly with the Carrier. Client understands that Estimated Rate contract reflects estimated the cost and is a subject for driver confirmation. In case any alternative offers are received from the carriers they will be passed to the client for his consideration. A customer has the right to accept or reject any offer. Client agrees not to hold INSTATOW LLC liable for any rate differences between Estimate Rate and Final Rate. Client agrees to hold INSTATOW LLC of all liability and responsibility arising from issues related to misrepresentation of weight; modification or vehicle conditions as well as Carrier malfunction.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">5. Prices are subject to change due to the fluctuations in car shipping market. If there are any changes to the original agreement, INSTATOW LLC will inform the client prior to assigning a carrier, for final confirmation. Customer agrees not to hold INSTATOW LLC responsible for rate change or any losses related.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">6. INSTATOW LLC will not charge the Deposit (which constitutes INSTATOW LLC service fee) until Client&rsquo;s vehicle is picked up by the Carrier assigned for shipment. However, once the vehicle(s) is(are) dispatched and a Carrier has been scheduled to pick up Client&rsquo;s vehicle INSTATOW LLC fee/deposit is due. Upon dispatching vehicle(s) to the Carrier selected and sending information about the Carrier to the Client, Client accepts the services from INSTATOW LLC to be satisfactory and complete and agrees not to hold INSTATOW LLC liable for any delays, damages, or not proper service provided by the Carrier. Any service fees or deposits unpaid by the time of delivery will be added to the remaining balance and either collected by Carrier on delivery or charged on the credit card provided in this agreement before the vehicle(s) will be released at delivery. All deposits and service fees are final and on-refundable. Client agrees not to hold INSTATOW LLC liable for Carrier&rsquo;s inability to deliver vehicle (vehicles), or for any damages. Client agrees and understands that such cases should be solved between the Carrier and The Client directly. Client bears full responsibility to do its due diligence related to the Carrier, Carrier&rsquo;s insurance and ability to provide necessary services. In the event Client is not satisfied it shall notify INSTATOW LLC and INSTATOW LLC is obligated to find a new Carrier. Any delay due to change of Carrier by the Client shall be the sole responsibility of the Client and INSTATOW LLC shall not be liable for any costs incurred</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">vehicle &lsquo;sown power at all times during shipment unless clearly noted on Client&rsquo;s order as non-running or inoperable(INOP). INOP vehicles must roll, steer and brake. If vehicle does not meet all three of these conditions, additional fees may apply. Vehicles that become on-operational during shipment, for any reason, will be subject to an additional, industry standard, non-operational fee of One Hundred and Fifty Dollars ($150.00). If vehicle is INOP and Carrier cannot physically reach the pick up or delivery location, a local tow truck may be used to assist in the service at the expense of Client. Also, any Client shipping INOP vehicle(s) may be required to help load or unload at Carrier&rsquo;s discretion.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">8. Client agrees and understands that vehicle(s) must be free of cargo as neither INSTATOW LLC nor Carrier are licensed or insured to handle the transportation of &ldquo;Household Goods&rdquo;. Damage to, loss of, or fines issued to Carrier resulting from any unauthorized cargo present in vehicle during shipment are the sole responsibility of Client. In addition, Client must prepare vehicle for transport by providing all keys, disarming and providing necessary remotes for any alarm systems, removing tags, plates and easy passes, and removing or retracting all antennas, loose items and/or protruding accessories from vehicle. No electronic equipment, valuables, plants, live pets, alcohol, drugs or firearms may be left in the vehicle. INSTATOW LLC and Carrier may not be held responsible for any damage to, loss of or damage caused by items left in Client&rsquo;s vehicle during transport. Carrier may silence alarm by any means.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">9. It is Client&rsquo;s responsibility to ensure that vehicle(s) is(are) ready to be released to the chosen Carrier by the projected pick update provided by Client at the time of order placement. Failure to release vehicle(s) for any reason (including but not limited to: storage, auction, port, towing, mechanical, purchase fees, scheduling or personal issues, etc. ) may result in cancellation and/or a&lsquo;Dry Run&rsquo; fee. Standard fee for &lsquo;Dry-Run&rsquo; is Two Hundred Dollars ($200.00). Client may elect to reschedule a new Carrier through INSTATOW LLC (additional fees apply). All deposits are final and non-refundable.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">10. Customer agrees that INSTATOW LLC has the right to reject (cancel) any order for any reason at any time.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">11. Carrier will be in touch with Client or Agent by phone at the numbers provided by Client in order to schedule an appointment for pickup and delivery of vehicle(s). It is Client&rsquo;s sole responsibility to verify that all contact phone numbers and email addresses given to INSTATOW LLC, and consequently Carrier, are correct. In the event Client or Agent is unable to meet Carrier at the appointed time for delivery and/or make payment of balance due, vehicle(s) may be stored at a facility chosen by Carrier at Client&rsquo;s expense. INSTATOW LLC will not be held responsible for any storage fees.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">12. Payments for the balance due to Carrier (COD) must be made on or before delivery of vehicle(s) unless payment on pick-up(COP) is prearranged or payment was made in full to INSTATOW LLC at the time of order placement (Full-Payment). All COD payments must be made directly to Carrier in the form of cash, cashier&rsquo;s check or money order payable to Carrier&rsquo;s company name ONLY. In the event the client decides to make a full payment with a credit card, the order will be subject to a 4% service charge.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">13. INSTATOW LLC will not be responsible for demurrage at any Port Facilities. For Hawaiian / Alaskan / Puerto Rican transports, payment for the sea portion MUST be issued by client BEFORE vehicle arrives at the port. Once an order is received, a booking number will be provided to client with instructions for issuing payment. Failure to do so may cause delays and /or additional storage fees.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">14. This contract is subject to all the terms and conditions of Carrier&rsquo;s straight bill of lading and any liability exclusions therein. INSTATOW LLC has no responsibility or liability for any damage to vehicle(s) and/or the contents of said vehicle(s) during transport or at any other time. Client or Agent should under no circumstances release or receive vehicle(s) from Carrier without an inspection report (Bill of Lading/BOL) regardless of the time of day or weather conditions. Carrier and Client, or Agent, are required to verify, sign and obtain a copy of both pick up and delivery inspection reports. Failure to do so may result in Client&rsquo;s inability to file a damage claim. It&rsquo;s Client&rsquo;s responsibility to mark mileage on odometer during pickup procedures. Any changes on odometer must be reflected on the Bill of Lading and signed by the Carrier on delivery location. Carrier&rsquo;s insurance will ONLY process claims for damages due to Carrier&rsquo;s own negligence. Damage must be reported to INSTATOW LLC within 24 hours of delivery and clearly listed on the BOL and signed by Carrier&rsquo;s driver, no exceptions. In the event there is damage during transport, Client (or designated Agent) must note those damages on the final inspection report, pay the remaining balance stated in this agreement (all monies owed for transport must be paid) and then contact Carrier&rsquo;s head office as well as Carrier&rsquo;s insurance company. Client will have to submit in writing a description of damage, clear pictures, and 2 estimates within 10 days of receipt of said vehicle directly to the designated carrier and his insurance company for any resolution to be initiated. Failure to note any damage on the final inspection report releases Carrier of any liability and could result in the inability to process a damage claim. Client agrees that INSTATOW LLC is not liable for any property damage claims to Client&rsquo;s vehicle and that his, her or its sole remedy is against the Carrier. Client agrees and understands that INSTATOW LLC is a registered transportation and property broker and is acting solely in the capacity of a broker. Client allows INSTATOW LLC to contract with other licensed and insured Motor Carrier(s), (hereinafter referred to as &ldquo;Carrier&quot;), to transport the vehicle(s) described in this shipping order. INSTATOW LLC and Carrier reserve the right to use multiple modes of transportation, including but not limited to truck, rail and ship.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Client further agrees and understands that INSTATOW LLC sole responsibility in the transaction between the client and INSTATOW LLC is to procure a carrier for shipment of the client&rsquo;s property. Client understands that INSTATOW LLC never takes possession of, transports, or delivers the Client&rsquo;s property.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Client agrees and understands that all claims for damage to property arising out or occurring during the taking possession of, transporting, or delivery of Client&rsquo;s property falls under the Carmack Amendment if the transport is interstate.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">As outlined in Section 10761 of the Interstate Commerce Act (49 USC 10761) the payment of freight charges may not be postponed due to alleged loss or damage. These charges should be paid in full and the portion applicable to the lost or damaged item should be included in the freight claim.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">The following items are important to remember:</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">a) Claims and payment of freight charges are two entirely different transactions.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">b) ICC regulations prohibit withholding the payment of freight bills due to a pending claim. (Administrative Ruling No. 128)</span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;"><br></span><span style="font-size:11pt;font-family:Calibri,sans-serif;">c) Without payment of the freight charges, payment for transportation has not been made. A valid claim will not be paid until freight charges are made.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">15. Carrier accepts the responsibility of vehicle after pre-inspection is done and Bill of Lading is signed by the Client. Carrier responsibility will end when the vehicle is delivered and Client signs final Bill of Lading inspection.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">16. Client agrees and understands that vehicle is supposed to be released only to the assigned by INSTATOW LLC. In case the Client releases the vehicle to the Carrier that was not assigned by INSTATOW LLC, INSTATOW LLC will not be held liable. It&rsquo;s Client&rsquo;s responsibility to check MC number or company name of the Carrier on pickup location and make sure it&rsquo;s the same as in confirmation email sent by INSTATOW LLC.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">17. Neither INSTATOW LLC nor Carrier can be held responsible for damages caused by vandalism, acts of God (hail, fire, sandstorms, flooding, snow, tornadoes, earthquakes, hurricanes, etc. ), objects flying from the road or objects falling from the sky during transport.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">18. Client shall, in their absence, designate a person to act as their agent at the point of pickup and/or delivery if for any reason they are unavailable.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">19. All Carriers selected by INSTATOW LLC must maintain the required insurance to protect Client&rsquo;s vehicle(s) during transport. Once vehicle(s) have been dispatched to the selected Carrier, INSTATOW LLC will email Client a copy of Carrier&rsquo;s Operating Authority along with a copy of the active insurance, as well as, any and all pertinent contact information for Carrier. Copies of Carrier&rsquo;s direct bill of lading must be obtained from the Carrier&rsquo;s driver and/or Carrier&rsquo;s office at the phone numbers provided. INSTATOW LLC grants their clients the right and ability to refuse the service of the selected Carrier based on this or any other information and to request to be set up with a different Carrier by INSTATOW LLC. Refusal of Carrier must be done at least 24hours in advance of scheduled pick up and will result in a $75 rescheduling fee that will be charged in addition to the deposit on the credit card provided.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">20. In the event that Carrier is unable to safely access the pickup or delivery addresses given by Client (due to, but not limited to entrance restrictions, low hanging branches, and/or narrow streets), Client agrees to meet Carrier at a nearby location in order for Carrier to safely perform his service. Inability to meet Carrier at pick up and/or delivery may result in additional fees.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">21. Client warrants that he/she will pay the full transportation price due to INSTATOW LLC /Carrier in full and will not try to offset any dispute for damage claims and/or delays etc. from freight (transport) charges. It is Client&apos;s responsibility to provide payment when Carrier arrives- unless the balance has been pre-paid in full. Client agrees that if the payment cannot be made, the vehicle will be stored, at Client&apos;s expense, until Client pays in full all transport charges. Should Client be unable to accept delivery for any reason, the vehicle will be placed in storage. Any and all storage and re-delivery charges will be the responsibility of Client.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">22. Client understands that the vehicle(s) will be driven onto and off the truck at the driver&rsquo;s discretion. Carrier is authorized to operate and transport Client&apos;s motor vehicle between its pickup location and the destination set forth on the shipping order and Bill of Lading.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">23. INSTATOW LLC asks for 1-5 business days starting at the first available date provided by Client (applies only to standard stockcars, SUV, Pickup Trucks, and Motorcycles) to assign a carrier to a Client&apos;s load. If INSTATOW LLC fails to pick up Client&rsquo;s vehicle within 5 business days from the first available date Client can opt out of this agreement with no penalties. If this agreement is canceled by Client any time prior to or within 5 business days from the first available date for vehicle pick up provided by Client and a carrier hasn&rsquo;t been assigned for such transport, a $95 cancellation fee will be charged to the credit card provided at the time of booking.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">24. Client shall defend, indemnify, and hold harmless INSTATOW LLC from any and all actual or alleged claims, demands, causes of action, liability, loss, damage and/or injury (to property or persons, including without limitation wrongful death), whether brought by an individual or other entity, imposed by a court of law or by administrative action of any federal state or local agency, arising out of or incident to any acts, omissions, negligence, or willful misconduct of INSTATOW LLC, or the Carrier, its personnel, employees, agents, or contractors in connection with or arising out of INSTATOW LLC or the Carrier&rsquo;s actions. The indemnification includes, without limitation, the payment of all penalties, fines, judgments, awards, attorney&rsquo;s fees, and related costs or expenses, and any reimbursements to INSTATOW LLC for all legal expenses and costs incurred by it.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">25. Client agrees and understands that these terms and conditions are the only contracts between Client and INSTATOW LLC. This document is binding as it supersedes any and all verbal or written communications, and as such may not be changed or altered by INSTATOW LLC, Client or Agent. INSTATOW LLC reserves the right to change these terms and conditions at any time without previous notice.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">26. This agreement shall be governed by and construed in accordance with the laws of the State of Florida. The parties further agree that any legal action arising out of this agreement must be filed in a court of jurisdiction within Broward County, Florida and that INSTATOW LLC liability is limited to the amount of INSTATOW LLC service fee only. Client hereby submits to the jurisdiction of such courts and waives any right to jurisdiction in any other location.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">27. INSTATOW LLC and/or its agents shall never be responsible for such force majeure events: - Damage not clearly noted on the Bill of Lading (inspection report), regardless of the time of day or weather conditions. -Damage to the undercarriage, suspension, brakes, alignment, tuning, exhaust system, electrical system or battery as no evaluation or inspection of the previous condition of such parts is performed before pick up. -Damage to antennas (INSTATOW LLC strongly suggests retracting or removing of any and all antennas). -Damage to or loss of personal items or non-stock equipment including (but not limited to) audio and/or video systems, GPS equipment, tracking devices, phones and power windows/mirrors. -Fines due to personal items inside the vehicle(s).-Damage caused by objects flying from the road (rock chips, windshields, etc. ). -Damage to cloth or vinyl roofs older than 2 years.-Damage caused by leaking fluids during transport, such as motor oil, transmission fluid, battery acid, coolant, antifreeze fluid, power steering fluid. -Damage to driveways, buildings, walls, doors, gates, garages, yards, trees, plants, sidewalks, fences, awnings mailboxes or nearby vehicles. -Damage caused by Acts of God (hail, fire, sandstorms, flooding, snow, tornadoes, earthquakes, hurricanes, etc. ). &ndash; Damage caused by acts of a public enemy, acts of terrorism, riots, strikes, labor disputes, fires,</span><span style="font-size:8pt;font-family:Verdana,sans-serif;">&nbsp;</span><span style="font-size:11pt;font-family:Calibri,sans-serif;">explosions, floods, acts or orders of civil or military authorities, or other causes beyond the reasonable control of the party declaring the force majeure events. &ndash; Clients should maintain their own insurance for these reasons. If the vehicle is valued at a higher than market rate, we suggest you purchase a special insurance rider.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">28. By either submitting your order online, sending us your order by fax or by email, INSTATOW LLC understands you are placing your order and accept the terms and conditions (in lieu of your signature) found here and on INSTATOW LLC website(www.truecarriers.com).</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Cancellation &amp; Refund Policy</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Refunds will be processed within 48 business hours of the cancellation request.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Cancellation of an order must be submitted in writing via email sent to sales@truecarriers.com. INSTATOW LLC does not accept or honor cancellations made via phone call.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Once a Carrier (transporter) has been assigned (dispatched) to a shipping order, INSTATOW LLC notifies Customer via email (to the email address provided at service booking).</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Reviews Policy</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Some reviews might participate in our review rebate program. If you review is taking part in our rebate program please indicate that it has been compensated. We encourage our customer to select our company not only based on online reviews but based on all public information they can find by themselves.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">International Orders</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">The car must be empty except for factory installed equipment. Indicate the serial number and give car&apos;s approximate value in U.S.dollars. The customer is responsible for the proper customs paperwork. (Ask the assigned Carrier for help with these documents.)Any order placed on our website that has a pickup and/or delivery location, such as a port, will be subject to an additional charge of $100. The booked price on our website https://www.truecarriers.com does not include the extra charge of $100.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">Final Clause</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">This agreement and any shipment here under is subject to all terms and conditions of Carrier&apos;s tariff and the uniform straight Bill of Lading, copies of which are available at the office of Carrier. This supersedes all prior written or oral representation of INSTATOW LLC and constitutes the entire agreement between Client and INSTATOW LLC and may not be changed except in writing signed by an officer of INSTATOW LLC. Client warrants that he, she or it has read this agreement in its entirety and by continuing with the transaction, fully understands and agrees to its terms. Further, Client waives any claims or defenses based in whole or in part on not reading, knowing, or understanding these terms and conditions and agrees to indemnify and hold harmless INSTATOW LLC for any fees or costs, including attorney&rsquo;s fees and costs, arising out of any claims or defenses asserted based upon not reading, having knowledge of, or understanding these terms and conditions.</span></p>
<p><span style="font-size:11pt;font-family:Calibri,sans-serif;">100 lbs of personal goods have to be confirmed with shipping agent upfront for specific carrier and does not apply to vehicles going to port</span></p>
        </div>
    </section>

    @endsection
